Document need for Gradle platform import
The latest fabric-protos require protobuf-java v4. This transitive
dependency requirement is specified for Maven consumers in the POM
file's dependency management, but a Gradle platform import is required
for Gradle consumers to apply this dependency management configuration.

Depending on the gRPC version used, failure to apply the specified
transitive dependency management can result in Gradle consumers
resolving protobuf-java v3 and experiencing the following runtume
failure:

    java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain

Signed-off-by: Mark S. Lewis <Mark.S.Lewis@outlook.com>